title: Fila2Jekyll
description: >- # this means to ignore newlines until "baseurl:"
  Tenemos una descripción apasionante y extremadamente útil.
baseurl: "/web" # the subpath of your site, e.g. /blog
url: http://www-04.ciber-egibide.eu # the base hostname & protocol for your site, e.g. http://example.com
repo-url: https://github.com/juleninigo/jekyll
repo-name: filajekyll
mail1: mail1@example.com
mail2: mail2@example.com
theme: minima
